# Generated by Django 4.2.20 on 2025-04-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faultDetection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_devices', to='faultDetection.hotel'),
        ),
    ]
