# Generated by Django 4.2.20 on 2025-04-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faultDetection', '0002_device_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_devices', to='faultDetection.hotel'),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='faultDetection.room'),
        ),
    ]
