# Generated by Django 4.2.20 on 2025-04-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultDetection', '0003_alter_device_hotel_alter_device_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faultalert',
            old_name='datetime',
            new_name='triggered_at',
        ),
        migrations.AddField(
            model_name='faultalert',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
