# Generated by Django 4.2.20 on 2025-04-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faultDetection', '0004_rename_datetime_faultalert_triggered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveFaultAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_fault_alerts', to='faultDetection.device')),
                ('sensor_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_sensor_point_fault', to='faultDetection.sensordata')),
            ],
            options={
                'unique_together': {('device', 'datapoint')},
            },
        ),
        migrations.CreateModel(
            name='PastFaultAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_fault_alerts', to='faultDetection.device')),
                ('sensor_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='past_sensor_point_fault', to='faultDetection.sensordata')),
            ],
        ),
        migrations.DeleteModel(
            name='FaultAlert',
        ),
    ]
