# Generated by Django 4.2.20 on 2025-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultDetection', '0005_activefaultalert_pastfaultalert_delete_faultalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
